
package com.github.ittalks.commons.example.ws.cxf.demo4.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 *
 */
@WebService(name = "HelloService", targetNamespace = "http://server.demo4.cxf.ws.example.commons.ittalks.github.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloService {


    /**
     *
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "say", targetNamespace = "http://server.demo4.cxf.ws.example.commons.ittalks.github.com/", className = "com.github.ittalks.commons.example.ws.cxf.demo4.client.Say")
    @ResponseWrapper(localName = "sayResponse", targetNamespace = "http://server.demo4.cxf.ws.example.commons.ittalks.github.com/", className = "com.github.ittalks.commons.example.ws.cxf.demo4.client.SayResponse")
    public String say(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

}
