
package com.github.ittalks.commons.example.webservice.jaxws.mapadapter.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FnWebServiceImplService", targetNamespace = "http://server.mapadapter.jaxws.webservice.example.commons.ittalks.github.com/", wsdlLocation = "http://127.0.0.1:9999/webservice?WSDL")
public class FnWebServiceImplService
    extends Service
{

    private final static URL FNWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException FNWEBSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName FNWEBSERVICEIMPLSERVICE_QNAME = new QName("http://server.mapadapter.jaxws.webservice.example.commons.ittalks.github.com/", "FnWebServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:9999/webservice?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FNWEBSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        FNWEBSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public FnWebServiceImplService() {
        super(__getWsdlLocation(), FNWEBSERVICEIMPLSERVICE_QNAME);
    }

    public FnWebServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FNWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public FnWebServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, FNWEBSERVICEIMPLSERVICE_QNAME);
    }

    public FnWebServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FNWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public FnWebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FnWebServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FnWebServiceImpl
     */
    @WebEndpoint(name = "FnWebServiceImplPort")
    public FnWebServiceImpl getFnWebServiceImplPort() {
        return super.getPort(new QName("http://server.mapadapter.jaxws.webservice.example.commons.ittalks.github.com/", "FnWebServiceImplPort"), FnWebServiceImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FnWebServiceImpl
     */
    @WebEndpoint(name = "FnWebServiceImplPort")
    public FnWebServiceImpl getFnWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server.mapadapter.jaxws.webservice.example.commons.ittalks.github.com/", "FnWebServiceImplPort"), FnWebServiceImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FNWEBSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw FNWEBSERVICEIMPLSERVICE_EXCEPTION;
        }
        return FNWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
