
package com.github.ittalks.commons.example.ws.jax.demo4.server;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MyWebServiceImpl", targetNamespace = "http://client.demo4.jax.ws.example.commons.ittalks.github.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MyWebServiceImpl {


    /**
     * 
     * @return
     *     returns com.github.ittalks.commons.example.ws.jax.demo4.server.MyRoleArray
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRoles", targetNamespace = "http://client.demo4.jax.ws.example.commons.ittalks.github.com/", className = "com.github.ittalks.commons.example.ws.jax.demo4.server.GetRoles")
    @ResponseWrapper(localName = "getRolesResponse", targetNamespace = "http://client.demo4.jax.ws.example.commons.ittalks.github.com/", className = "com.github.ittalks.commons.example.ws.jax.demo4.server.GetRolesResponse")
    public MyRoleArray getRoles();

}
