
package com.github.ittalks.commons.example.ws.jax.demo3.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MyWebServiceImpl", targetNamespace = "http://server.demo3.jax.ws.example.commons.ittalks.github.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MyWebServiceImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.github.ittalks.commons.example.ws.jax.demo3.client.Role>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRoleByUser", targetNamespace = "http://server.demo3.jax.ws.example.commons.ittalks.github.com/", className = "com.github.ittalks.commons.example.ws.jax.demo3.client.GetRoleByUser")
    @ResponseWrapper(localName = "getRoleByUserResponse", targetNamespace = "http://server.demo3.jax.ws.example.commons.ittalks.github.com/", className = "com.github.ittalks.commons.example.ws.jax.demo3.client.GetRoleByUserResponse")
    public List<Role> getRoleByUser(
            @WebParam(name = "arg0", targetNamespace = "")
                    User arg0);

}
