
package com.github.ittalks.commons.example.ws.cxf.integration.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ComplexUserService", targetNamespace = "http://server.integration.cxf.ws.example.commons.ittalks.github.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ComplexUserService {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    public void setUser(
            @WebParam(name = "arg0", partName = "arg0")
                    User arg0);

    /**
     * 
     * @param name
     * @return
     *     returns com.github.ittalks.commons.example.ws.cxf.integration.client.User
     */
    @WebMethod
    @WebResult(partName = "return")
    public User getUserByName(
            @WebParam(name = "name", partName = "name")
                    String name);

}
